digitalIdentity:  loc-general-demo-ui-neil-0324-api-route
method: Get
mode: Sync
encapsulation: true
name:  loc-general-demo-ui-neil-0324
path: /loc-general-demo-ui-neil-0324
dataProcessIds:
  - 6e04c019-25ce-46f9-a2b7-dfb98313ec0f
