digitalIdentity:  loc-general-demo-ui-neil-0325-api-route
method: Get
mode: Sync
encapsulation: true
name:  loc-general-demo-ui-neil-0325
path: /loc-general-demo-ui-neil-0325
dataProcessIds:
  - 1c93c017-50d1-40a1-add0-6326d89b776f
