digitalIdentity:  loc-general-demo-ui-neil-0325-api-route
method: Get
mode: Sync
encapsulation: true
name:  loc-general-demo-ui-neil-0401
path: /loc-general-demo-ui-neil-0401
dataProcessIds:
  - c86b3a18-7b02-44af-80f3-d4797af480b4
