version: 0.1.0
digitalIdentity: loc-general-demo-ui-neil-0401
name: loc-general-demo-ui-neil-0401
aggregatorLogic:
  digitalIdentity: loc-general-demo-ui-neil-0401-aggregator
  file: aggregator-logic.js
genericLogics:
  - digitalIdentity: loc-general-demo-ui-neil-0401-generic-1
    file: 1.js
