version: 0.1.0
digitalIdentity: loc-general-demo-ui-neil-0323
name: loc-general-demo-ui-neil-0323
aggregatorLogic:
  digitalIdentity: loc-general-demo-ui-neil-0323-aggregator
  file: aggregator-logic.js
genericLogics:
  - digitalIdentity: loc-general-demo-ui-neil-0323-generic-1
    file: 1.js
