version: 0.1.0
digitalIdentity: loc-general-demo-ui-neil-0324
name: loc-general-demo-ui-neil-0324
aggregatorLogic:
  digitalIdentity: loc-general-demo-ui-neil-0324-aggregator
  file: aggregator-logic.js
genericLogics:
  - digitalIdentity: loc-general-demo-ui-neil-0324-generic-1
    file: 1.js
